include(
    ":android",
    ":common:root",
    ":common:domain",
    ":common:database",
    ":common:tools",
    ":common:component:main",
    ":common:component:create",
    ":common:component:calendar",
    ":common:component:root"
)
